# -*- coding: utf-8 -*-
"""Sweetspot Indentification_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s-HetGnSZB_4aDVcVgXP17xlCUFo4F-r
"""

# ================================================
# 1. Upload eval_results.csv
# ================================================
from google.colab import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Create figures folder
os.makedirs("figures", exist_ok=True)

print("📤 Please upload your 'eval_results.csv' file")
uploaded = files.upload()

# Load the file
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

print(f"✅ Loaded {filename} successfully!")

# ================================================
# 2. Compute Simple Average TCR
# ================================================
df["TCR"] = (df["faithfulness"] +
             df["answer_relevancy"] +
             df["context_precision"]) / 3

# ================================================
# Plot 1: TCR vs Index Size (Main Sweet Spot Plot)
# ================================================
plt.figure(figsize=(13, 8))

sns.scatterplot(
    data=df,
    x="index_size_mb",
    y="TCR",
    hue="model",
    style="chunking",
    s=130,
    alpha=0.85,
    palette="tab10"
)

plt.title("TCR vs Index Size (MB) \n(Colored by Model • Shaped by Chunking)", fontsize=14, pad=20)
plt.xlabel("Index Size (MB) — Lower is Better")
plt.ylabel("Simple Average TCR — Higher is Better")
plt.grid(True, alpha=0.3)


# Move legend to the right side to prevent overlap
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left', title="Model & Chunking", fontsize=10)

plt.tight_layout()
plt.savefig("figures/tcr_vs_index.png", dpi=300, bbox_inches='tight')
plt.show()

# ================================================
# Plot 2: TCR vs RAM After
# ================================================
plt.figure(figsize=(13, 8))
sns.scatterplot(
    data=df,
    x="ram_after_mb",
    y="TCR",
    hue="model",
    style="chunking",
    s=130,
    alpha=0.85,
    palette="tab10"
)
plt.title("TCR vs RAM Usage After Inference (MB)", fontsize=14, pad=20)
plt.xlabel("RAM After Inference (MB) — Lower is Better")
plt.ylabel("Simple Average TCR — Higher is Better")
plt.grid(True, alpha=0.3)
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.savefig("figures/tcr_vs_ram.png", dpi=300, bbox_inches='tight')
plt.show()

# ================================================
# Plot 3: TCR vs Avg Latency
# ================================================
plt.figure(figsize=(13, 8))
sns.scatterplot(
    data=df,
    x="avg_latency_s",
    y="TCR",
    hue="model",
    style="chunking",
    s=130,
    alpha=0.85,
    palette="tab10"
)
plt.title("TCR vs Average Latency (seconds)", fontsize=14, pad=20)
plt.xlabel("Average Latency (seconds) — Lower is Better")
plt.ylabel("Simple Average TCR — Higher is Better")
plt.grid(True, alpha=0.3)
plt.legend(bbox_to_anchor=(1.02, 1), loc='upper left')
plt.tight_layout()
plt.savefig("figures/tcr_vs_latency.png", dpi=300, bbox_inches='tight')
plt.show()

print("\n✅ All plots generated successfully and saved in the 'figures/' folder!")

