# -*- coding: utf-8 -*-
"""Sweet spot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BF08wuDM-z4Jfq38ZncGzl1Z90HsaQnz
"""

import matplotlib.pyplot as plt

# Data (averaged across both LLMs)
strategies = ['SS-128', 'SS-256', 'SS-512', 'Semantic', 'SentWindow']
performance = [0.7475, 0.7688, 0.7525, 0.5613, 0.7375]
memory = [446.77, 253.85, 179.12, 181.75, 880.59]

plt.figure(figsize=(11, 8))

# Plot the points with different colors
colors = ['#1f77b4', '#2ca02c', '#d62728', '#9467bd', '#8c564b']
for i, strat in enumerate(strategies):
    plt.scatter(memory[i], performance[i], s=120, color=colors[i], edgecolor='black', zorder=5)
    plt.annotate(strat, (memory[i], performance[i]),
                 xytext=(0, 15), textcoords='offset points',
                 ha='center', fontsize=11, fontweight='bold')

# Highlight SS-256 as sweet spot with a star
plt.scatter(253.85, 0.7688, s=200, color='#ff7f0e', edgecolor='black', marker='*', zorder=10)

# Sweet spot annotation - moved lower and to the right to avoid title clash
plt.annotate('Sweet Spot\nSS-256\n(Highest overall performance\nwith balanced memory)',
             xy=(253.85, 0.7688),
             xytext=(380, 0.68),   # Adjusted position: lower and right
             arrowprops=dict(facecolor='red', shrink=0.05, width=3, headwidth=8),
             bbox=dict(boxstyle="round,pad=0.8", facecolor="#ffff99", alpha=0.95, edgecolor='black'),
             fontsize=11, ha='left', va='center')

# Labels and title
plt.xlabel('Mean Memory Usage (KB)', fontsize=12, fontweight='bold')
plt.ylabel('Average Performance Score\n(Faithfulness, Answer Relevance,\nContext Relevance, Task Completion)',
           fontsize=12, fontweight='bold', labelpad=15)

plt.title('Chunking Strategy: Performance vs. Memory Usage\nSweet Spot Identification for Balanced Configuration',
          fontsize=14, fontweight='bold', pad=25)

plt.grid(True, linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()